FROM postgres:16-alpine

# Set environment variables for user, password, and database
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=adminpassword
ENV POSTGRES_DB=currencydb

EXPOSE 5432


#docker run -d -v "$(pwd)/data:/var/lib/postgresql/data" -p 5432:5432 --name assignment-postgres  assignment-postgres-image